<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="6" total="10" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Enter Time-Track]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Invalid UN :admin]]>
    </line>
    <line>
      <![CDATA[Invalid pw :admin]]>
    </line>
    <line>
      <![CDATA[Element is Present]]>
    </line>
    <line>
      <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Error message is matching...........]]>
    </line>
    <line>
      <![CDATA[===========================,]]>
    </line>
    <line>
      <![CDATA[Invalid UN :admin]]>
    </line>
    <line>
      <![CDATA[Invalid pw :mang]]>
    </line>
    <line>
      <![CDATA[Element is Present]]>
    </line>
    <line>
      <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Error message is matching...........]]>
    </line>
    <line>
      <![CDATA[===========================,]]>
    </line>
    <line>
      <![CDATA[Invalid UN :admin]]>
    </line>
    <line>
      <![CDATA[Invalid pw :admin]]>
    </line>
    <line>
      <![CDATA[Element is Present]]>
    </line>
    <line>
      <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
    </line>
    <line>
      <![CDATA[Error message is matching...........]]>
    </line>
    <line>
      <![CDATA[===========================,]]>
    </line>
    <line>
      <![CDATA[Invalid UN :admin]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Element is not Present]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Login]]>
    </line>
    <line>
      <![CDATA[Tittle is matching :actiTIME - Enter Time-Track]]>
    </line>
    <line>
      <![CDATA[Element is not Present]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="339963" started-at="2020-02-01T04:06:23Z" finished-at="2020-02-01T04:12:03Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="339963" started-at="2020-02-01T04:06:23Z" finished-at="2020-02-01T04:12:03Z">
      <class name="com.actitime.tests.ValidLoginLogoutTest">
        <test-method status="PASS" signature="precondition()[pri:0, instance:com.actitime.tests.ValidLoginLogoutTest@18067a5]" name="precondition" is-config="true" duration-ms="46506" started-at="2020-02-01T04:06:24Z" finished-at="2020-02-01T04:07:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="PASS" signature="testValidLoginLogout()[pri:1, instance:com.actitime.tests.ValidLoginLogoutTest@18067a5]" name="testValidLoginLogout" duration-ms="26081" started-at="2020-02-01T04:07:10Z" finished-at="2020-02-01T04:07:36Z">
          <reporter-output>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Enter Time-Track]]>
            </line>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLoginLogout -->
        <test-method status="PASS" signature="postcondition(org.testng.ITestResult)[pri:0, instance:com.actitime.tests.ValidLoginLogoutTest@18067a5]" name="postcondition" is-config="true" duration-ms="2546" started-at="2020-02-01T04:07:36Z" finished-at="2020-02-01T04:07:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidLoginLogout status=SUCCESS method=ValidLoginLogoutTest.testValidLoginLogout()[pri:1, instance:com.actitime.tests.ValidLoginLogoutTest@18067a5] output=Tittle is matching :actiTIME - Login]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- com.actitime.tests.ValidLoginLogoutTest -->
      <class name="com.actitime.tests.InvalidLoginTest">
        <test-method status="PASS" signature="startTest()[pri:0, instance:com.actitime.tests.InvalidLoginTest@1ef45e3]" name="startTest" is-config="true" duration-ms="750" started-at="2020-02-01T04:06:23Z" finished-at="2020-02-01T04:06:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="PASS" signature="precondition()[pri:0, instance:com.actitime.tests.InvalidLoginTest@1ef45e3]" name="precondition" is-config="true" duration-ms="32371" started-at="2020-02-01T04:07:39Z" finished-at="2020-02-01T04:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testInvalidLogin()[pri:2, instance:com.actitime.tests.InvalidLoginTest@1ef45e3]" name="testInvalidLogin" duration-ms="33119" started-at="2020-02-01T04:08:12Z" finished-at="2020-02-01T04:08:45Z">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[stale element reference: element is not attached to the page document
  (Session info: chrome=79.0.3945.130)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DIVYA-PC', ip: '192.168.43.88', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.130, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: E:\Users\Divya\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:50140}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 644f81e5baf6c6173f263e370b3b2cb7]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=79.0.3945.130)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DIVYA-PC', ip: '192.168.43.88', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 79.0.3945.130, chrome: {chromedriverVersion: 79.0.3945.36 (3582db32b3389..., userDataDir: E:\Users\Divya\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:50140}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 644f81e5baf6c6173f263e370b3b2cb7
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy11.sendKeys(Unknown Source)
at com.actitime.pages.LoginPage.enterUserName(LoginPage.java:40)
at com.actitime.tests.InvalidLoginTest.testInvalidLogin(InvalidLoginTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[Invalid UN :admin]]>
            </line>
            <line>
              <![CDATA[Invalid pw :admin]]>
            </line>
            <line>
              <![CDATA[Element is Present]]>
            </line>
            <line>
              <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Error message is matching...........]]>
            </line>
            <line>
              <![CDATA[===========================,]]>
            </line>
            <line>
              <![CDATA[Invalid UN :admin]]>
            </line>
            <line>
              <![CDATA[Invalid pw :mang]]>
            </line>
            <line>
              <![CDATA[Element is Present]]>
            </line>
            <line>
              <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Error message is matching...........]]>
            </line>
            <line>
              <![CDATA[===========================,]]>
            </line>
            <line>
              <![CDATA[Invalid UN :admin]]>
            </line>
            <line>
              <![CDATA[Invalid pw :admin]]>
            </line>
            <line>
              <![CDATA[Element is Present]]>
            </line>
            <line>
              <![CDATA[Actual error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Expected error Meassge is :Username or Password is invalid. Please try again.]]>
            </line>
            <line>
              <![CDATA[Error message is matching...........]]>
            </line>
            <line>
              <![CDATA[===========================,]]>
            </line>
            <line>
              <![CDATA[Invalid UN :admin]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="FAIL" signature="postcondition(org.testng.ITestResult)[pri:0, instance:com.actitime.tests.InvalidLoginTest@1ef45e3]" name="postcondition" is-config="true" duration-ms="1298" started-at="2020-02-01T04:08:45Z" finished-at="2020-02-01T04:08:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInvalidLogin status=FAILURE method=InvalidLoginTest.testInvalidLogin()[pri:2, instance:com.actitime.tests.InvalidLoginTest@1ef45e3] output=Tittle is matching :actiTIME - Login]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/apache/commons/io/FileUtils]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at om.actitime.generic.GenericUtils.getscreenshots(GenericUtils.java:21)
at om.actitime.generic.BaseTest.postcondition(BaseTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
        <test-method status="PASS" signature="stopTest()[pri:0, instance:com.actitime.tests.InvalidLoginTest@1ef45e3]" name="stopTest" is-config="true" duration-ms="2009" started-at="2020-02-01T04:12:01Z" finished-at="2020-02-01T04:12:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopTest -->
      </class> <!-- com.actitime.tests.InvalidLoginTest -->
      <class name="com.actitime.tests.VerfiyVersionTest">
        <test-method status="PASS" signature="precondition()[pri:0, instance:com.actitime.tests.VerfiyVersionTest@ecd4b]" name="precondition" is-config="true" duration-ms="37813" started-at="2020-02-01T04:08:46Z" finished-at="2020-02-01T04:09:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testVerifyVersion()[pri:3, instance:com.actitime.tests.VerfiyVersionTest@ecd4b]" name="testVerifyVersion" duration-ms="30838" started-at="2020-02-01T04:09:24Z" finished-at="2020-02-01T04:09:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.actitime.pages.BasePage.verifyElement(BasePage.java:45)
at com.actitime.pages.LoginPage.verifyVersion(LoginPage.java:58)
at com.actitime.tests.VerfiyVersionTest.testVerifyVersion(VerfiyVersionTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[Element is not Present]]>
            </line>
          </reporter-output>
        </test-method> <!-- testVerifyVersion -->
        <test-method status="FAIL" signature="postcondition(org.testng.ITestResult)[pri:0, instance:com.actitime.tests.VerfiyVersionTest@ecd4b]" name="postcondition" is-config="true" duration-ms="544" started-at="2020-02-01T04:09:55Z" finished-at="2020-02-01T04:09:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testVerifyVersion status=FAILURE method=VerfiyVersionTest.testVerifyVersion()[pri:3, instance:com.actitime.tests.VerfiyVersionTest@ecd4b] output=Tittle is matching :actiTIME - Login]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/apache/commons/io/FileUtils]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at om.actitime.generic.GenericUtils.getscreenshots(GenericUtils.java:21)
at om.actitime.generic.BaseTest.postcondition(BaseTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- com.actitime.tests.VerfiyVersionTest -->
      <class name="com.actitime.tests.VerifyBuildNoTest">
        <test-method status="PASS" signature="precondition()[pri:0, instance:com.actitime.tests.VerifyBuildNoTest@bf9759]" name="precondition" is-config="true" duration-ms="42856" started-at="2020-02-01T04:09:56Z" finished-at="2020-02-01T04:10:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="testVerifyBuildNo()[pri:4, instance:com.actitime.tests.VerifyBuildNoTest@bf9759]" name="testVerifyBuildNo" duration-ms="81611" started-at="2020-02-01T04:10:38Z" finished-at="2020-02-01T04:12:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.actitime.pages.BasePage.verifyElement(BasePage.java:45)
at com.actitime.pages.EnterTimeTrackerPage.verifyBuildNo(EnterTimeTrackerPage.java:48)
at com.actitime.tests.VerifyBuildNoTest.testVerifyBuildNo(VerifyBuildNoTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Login]]>
            </line>
            <line>
              <![CDATA[Tittle is matching :actiTIME - Enter Time-Track]]>
            </line>
            <line>
              <![CDATA[Element is not Present]]>
            </line>
          </reporter-output>
        </test-method> <!-- testVerifyBuildNo -->
        <test-method status="FAIL" signature="postcondition(org.testng.ITestResult)[pri:0, instance:com.actitime.tests.VerifyBuildNoTest@bf9759]" name="postcondition" is-config="true" duration-ms="810" started-at="2020-02-01T04:12:00Z" finished-at="2020-02-01T04:12:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testVerifyBuildNo status=FAILURE method=VerifyBuildNoTest.testVerifyBuildNo()[pri:4, instance:com.actitime.tests.VerifyBuildNoTest@bf9759] output=Tittle is matching :actiTIME - Login]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/apache/commons/io/FileUtils]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at om.actitime.generic.GenericUtils.getscreenshots(GenericUtils.java:21)
at om.actitime.generic.BaseTest.postcondition(BaseTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- com.actitime.tests.VerifyBuildNoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
